#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  6 14:34:15 2018

@author: bryceanderson
"""

import nltk
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))
def prettify(string):
    string = string.replace(",","")
    string = string.replace(".","")
    string = string.replace("'","")
    string = string.replace("!","")
    string = string.replace("?","")
    string = string.replace('"',"")
    string = string.replace("'","")
    string = string.replace(";","")
    string = string.replace(":","")
    string = string.replace("\n"," ")
    string = string.replace("(","")
    string = string.replace(")","")
    string = string.replace("-","")
    string = string.replace("`","")
    string = string.lower()
    return string
def prep(string):
    tokens = nltk.word_tokenize(string)
    tokens = nltk.Text(tokens)
    return tokens
#%%
doc = open('raplyrics.txt','r')
raw=doc.read()
raw = prettify(raw)
tokens = prep(raw)
filtered_sentence = []
for w in tokens:
    if w not in stopwords:
        filtered_sentence.append(w)
allwords = nltk.FreqDist(w.lower() for w in filtered_sentence)
wds = list(allwords.keys())
vals = list(allwords.values())
zipwords = zip(vals, wds)
zipwords = sorted(zipwords, reverse=True)


